# Generated by Django 3.2.9 on 2022-01-11 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_fcrit_only',
            field=models.BooleanField(default=False, verbose_name='Is Event Only For FCRIT Students'),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('C', 'Cultural'), ('T', 'Technical')], max_length=1, verbose_name='Category'),
        ),
    ]
