# Generated by Django 3.2.9 on 2022-01-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20220111_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('C', 'Cultural'), ('T', 'Technical'), ('S', 'Sports')], max_length=1, verbose_name='Category'),
        ),
    ]
