# Generated by Django 3.2.9 on 2022-01-12 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='transaction',
        ),
    ]
