# Generated by Django 3.2.9 on 2022-02-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_event_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Is Featured'),
        ),
        migrations.AlterField(
            model_name='event',
            name='entry_fee',
            field=models.IntegerField(default='[100, 200, 300]', verbose_name='Entry Fee'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_fcrit_only',
            field=models.BooleanField(default=False, verbose_name='Is Event only for FCRIT Students'),
        ),
        migrations.AlterField(
            model_name='event',
            name='seats',
            field=models.IntegerField(default=0, verbose_name='Event Seats(0 at start)'),
        ),
    ]
