# Generated by Django 3.2.9 on 2022-01-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20220111_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='order_payment_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
        migrations.AddField(
            model_name='transaction',
            name='upi_transaction_id',
            field=models.CharField(default=123456789, max_length=36, verbose_name='UPI Transaction Id'),
            preserve_default=False,
        ),
    ]
