# Generated by Django 3.2.9 on 2022-01-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='donation_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
