# Generated by Django 3.2.9 on 2021-12-29 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('roll_no', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Roll Number')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Name')),
                ('avatar', models.CharField(blank=True, max_length=256, null=True, verbose_name='Avatar Image')),
                ('department', models.CharField(blank=True, choices=[('COMP', 'Computer'), ('IT', 'IT'), ('EXTC', 'EXTC'), ('MECH', 'Mechanical'), ('ELEC', 'Electrical'), ('OTHER', 'Other')], max_length=10, null=True, verbose_name='Department')),
                ('semester', models.SmallIntegerField(blank=True, null=True, verbose_name='Semester')),
                ('phone_no', models.CharField(blank=True, max_length=32, verbose_name='Phone Number')),
                ('is_phone_no_verified', models.BooleanField(default=False, verbose_name='Is Phone Number Verified')),
                ('cart', models.TextField(default='[]', verbose_name='Cart JSON (DONT FILL THIS)')),
                ('is_from_fcrit', models.BooleanField(default=True, verbose_name='Is From FCrit')),
                ('money_owed', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Money Owed')),
                ('has_filled_profile', models.BooleanField(default=False, verbose_name='Has Filled Profile')),
                ('criteria', models.TextField(default='{"C": 0, "T": 0}', verbose_name='Criteria JSON (DONT FILL THIS)')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
