# Generated by Django 3.2.9 on 2021-12-29 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('department', models.CharField(choices=[('COMP', 'Computer'), ('IT', 'IT'), ('EXTC', 'EXTC'), ('MECH', 'Mechanical'), ('ELEC', 'Electrical'), ('OTHER', 'Other')], max_length=10, verbose_name='Department')),
                ('semester', models.SmallIntegerField(verbose_name='Semester')),
                ('phone_no', models.CharField(max_length=32, verbose_name='Phone Number')),
                ('college', models.CharField(max_length=256, verbose_name='College')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Is Approved')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='college',
            field=models.CharField(default='FCRIT, Vashi.', max_length=256, verbose_name='College'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_from_fcrit',
            field=models.BooleanField(default=True, verbose_name='Is From FCRIT'),
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('part_id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False, unique=True, verbose_name='Participation Id')),
                ('team_name', models.CharField(max_length=256, verbose_name='Team Name')),
                ('transaction_id', models.CharField(blank=True, max_length=36, null=True, verbose_name='Transactions Id')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is Paid')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is Verified')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='events.event')),
                ('members', models.ManyToManyField(related_name='participations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
