# Generated by Django 3.2.9 on 2022-02-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_participation_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='criteria',
            field=models.TextField(default='{"C": 0, "T": 0, "S": 0}', verbose_name='Criteria JSON (DONT FILL THIS)'),
        ),
    ]
